version: "3.9"

services:
  db:
    image: postgres:15
    container_name: vulndb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vulndb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    restart: always

  redis:
    image: redis:7
    container_name: vulredis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1"]
    restart: always

  app:
    build: .
    container_name: vulndashboard
    working_dir: /app
    command: ["python", "app.py"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vulndb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - VULNERS_API_KEY=${VULNERS_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

  worker:
    build: .
    container_name: vulndashboard-worker
    working_dir: /app
    command: ["celery", "-A", "celery_app.celery", "worker", "--loglevel=info", "--concurrency=1"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      app:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vulndb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
      - VULNERS_API_KEY=${VULNERS_API_KEY}
    volumes:
      - .:/app
    restart: always

volumes:
  pgdata:
